require("impatient")
-- require("impatient").enable_profile()
require("mrgeek.core")
require("mrgeek.options")
require("mrgeek.theme")
require("mrgeek.commands")
require("mrgeek.autocommands")
require("mrgeek.lsp").setup()
